### ISSUE TITLE
References to ST429-6

### ISSUE THREAD

**Issue by jpviollet** [SMPTE/st429-6#4]
As part of the overall SMPTE D-Cinema specifications current update, Normative References are now un-dated – and my understanding is that we would only specify a date when an issue is known.

As I just indicated in https://github.com/SMPTE/st429-6/issues/1, ST 429-6 Amendment 1:2018 remains a problem for D-Cinema, and as such it feels safe in all standards referring to ST 429-6 (e.g., ST429-2, ST429-5, and now ST429-18 revised draft) to keep a note indicating something like "ST429-6 Amendment 1:2018 is NOT for use with D-Cinema applications". 

In fact, even if a newer version of ST 429-6 may clarify which Encrypted Essence Container Label value to use for D-Cinema, depending which revised standard will be published/appear on SMPTE web site first (e.g. ST 429-2 vs ST 429-6), the Amendment could become the latest ST429-6 version available (and therefore be applicable) for D-Cinema (for example if ST429-2 is published before ST429-6.) And because of the known issue on some implementation, it feels safe to clearly indicate the Amendment issue everywhere ST429-6 is referenced like done so far to be safe anyway. Hope it makes sense. Thank you.

_Note: The proposed addition is not for ST429-6 directly, but for all standards referring to ST429-6. I thought it would be easier to track if reported only once (e.g., here in ST429-6 repository), however if better to register this on Github differently, I'll be happy to do so, let me know._

**Comment by palemieux** [comment]
@jpviollet I suggest that:

* we change the semantics of the current frame-wrapped label to signal either clip- or frame-wrapped essence depending on the circumstances, and that we deprecate it. 
* introduce a new label that unambiguously signals frame-wrapped essence

This is similar to the approach taken by ST 422 to handle the _FU_ label.

ST 429-2 would state that the current frame-wrapped (but now deprecated) label is to be used for cinema applications.

See proposed text at https://github.com/SMPTE/st429-6-private/pull/1

**Comment by jpviollet** [comment]
Hello Pierre,

Adopting same approach as used in ST 422 seems indeed appropriate to me. That being said:

. ST 422 indicates that: _"FU" Undefined Frame-based wrapping is deprecated for new applications but still
in use in some applications_ . As such, ST 422 does NOT say that "FU" label is "deprecated" - it says it is deprecated for "new applications" only.
. To be clear about D-Cinema practice, ST 422 also explicitly mentions "D-Cinema applications" as using the FU Label, and it is described using the present tense (not the past tense), see page 6 NOTE 2:

"NOTE 2 D-Cinema applications, as specified in SMPTE ST 429-2, use Essence Container Label "FU" strictly with progressive pictures, i.e., an MXF file referenced by a D-Cinema Composition that conforms to SMPTE ST 429-2 uses progressive pictures."

. We should do the same here to avoid confusion. It feels even more important to me because when I first read the proposed revised text in ST429-6, I understood that the legacy label "should not be used in new implementations" instead of "in new applications". It took me couple more readings to realize the usage of the word "application" and its meaning - and I'm concerned that people that would not be aware of the issue may read this too quickly and understand that any new implementation should NOT use legacy label, especially if the NOTE explains that some application "applied" it to both frame/clip wrapped essence, instead of "still apply it".

. Also, stating that "While earlier editions of this document specified that it applied only to frame-wrapped essence" is only true for the Amendment 2018, but not for the 2006 version (that did not indicate either "frame" or "clip" wrapping)

. What about re-wording the NOTE as follows:

NOTE — The semantics of the label  060e2b34 04010107 0d010301 020b0100  depends on the circumstances. While ST429-6 Amendment 1:2018 specified that it applied only to frame-wrapped essence, the ST429-6:2006 edition did not indicate any "frame" or "clip" wrapped essence restriction, and some applications, such as D-Cinema applications as specified in SMPTE ST 429-2, apply it to both frame- and clip-wrapped essence. New applications are encouraged to use the label  060e2b34 0401010d 0d010301 020b0300  for frame-wrapped essence.

. And having ST 429-2 also require usage of this legacy label would indeed be good. 

Hope this makes sense, thank you.

**Comment by jpviollet** [comment]
And as a side note, byte 8 of the new proposed Frame Wrapped label may end up not being 0d probably.

**Comment by palemieux** [comment]
>  And as a side note, byte 8 of the new proposed Frame Wrapped label may end up not being 0d probably.

The version byte is fixed to `0x0d` for labels: https://registry.smpte-ra.org/view/draft/docs/Register%20(ALL)/UL%20version%20bytes/

**Comment by palemieux** [comment]
> the ST429-6:2006 edition did not indicate any "frame" or "clip" wrapped essence restriction,

Section 10.1 specified that the label applied to frame-wrapped essence.

![image](https://user-images.githubusercontent.com/4871350/222463138-2cd8c3d1-3866-45e8-9192-84c58e5ffca6.png)

**Comment by jpviollet** [comment]
Thank you for pointing out 429-6 section 10.1 table, as well as the smpte-ra page for version byte. I indeed missed this.

We can work on a rewording of the text around the Encrypted Essence Container Label - despite the Table in section 10.1, it still does not feel right to me to say that the document specified it "_applied only to frame wrapped essence_" (as section 4 did require its usage for "any track containing Encrypted Triplets", without further restriction - I agree tablet 10.1 makes it a little bit confusing)
